/* @pjs globalKeyEvents="true";
        font="data/HammersmithOne.ttf";
        preload="data/blankbutton.png,
                 data/turtlesback_bg_titlescreen01.png,

                 data/general/back.png,
                 data/general/play.png,
                 data/general/pause.png,
                 data/general/mute.png,
                 data/general/nomute.png,

                 data/uprooted/Branch-01.png,
                 data/uprooted/Branch-01-cosmetic.png,
                 data/uprooted/Branch-01-outline.png,
                 data/uprooted/Branch-02.png,
                 data/uprooted/Branch-02-cosmetic.png,
                 data/uprooted/Branch-02-outline.png,
                 data/uprooted/Branch-03.png,
                 data/uprooted/Branch-03-cosmetic.png,
                 data/uprooted/Branch-03-outline.png,
                 data/uprooted/Branch-04.png,
                 data/uprooted/Branch-04-cosmetic.png,
                 data/uprooted/Branch-04-outline.png,
                 data/uprooted/Branch-05.png,
                 data/uprooted/Branch-05-cosmetic.png,
                 data/uprooted/Branch-05-outline.png,
                 data/uprooted/Branch-06.png,
                 data/uprooted/Branch-06-cosmetic.png,
                 data/uprooted/Branch-06-outline.png,
                 data/uprooted/Branch-07.png,
                 data/uprooted/Branch-07-cosmetic.png,
                 data/uprooted/Branch-07-outline.png,
                 data/uprooted/Branch-08.png,
                 data/uprooted/Branch-08-cosmetic.png,
                 data/uprooted/Branch-08-outline.png,

                 data/uprooted/CollectItem-01.png,
                 data/uprooted/CollectItem-01-faded.png,
                 data/uprooted/CollectItem-01-highlight.png,
                 data/uprooted/CollectItem-01-outline.png,
                 data/uprooted/CollectItem-02.png,
                 data/uprooted/CollectItem-02-faded.png,
                 data/uprooted/CollectItem-02-highlight.png,
                 data/uprooted/CollectItem-02-outline.png,
                 data/uprooted/CollectItem-03.png,
                 data/uprooted/CollectItem-03-faded.png,
                 data/uprooted/CollectItem-03-highlight.png,
                 data/uprooted/CollectItem-04.png,
                 data/uprooted/CollectItem-04-faded.png,
                 data/uprooted/CollectItem-04-highlight.png,
                 data/uprooted/CollectItem-04-outline.png,
                 data/uprooted/CollectItem-05.png,
                 data/uprooted/CollectItem-05-faded.png,
                 data/uprooted/CollectItem-05-highlight.png,
                 data/uprooted/CollectItem-05-outline.png,
                 data/uprooted/CollectItem-06.png,
                 data/uprooted/CollectItem-06-faded.png,
                 data/uprooted/CollectItem-06-highlight.png,
                 data/uprooted/CollectItem-06-outline.png,
                 data/uprooted/CollectItem-07.png,
                 data/uprooted/CollectItem-07-faded.png,
                 data/uprooted/CollectItem-07-highlight.png,
                 data/uprooted/CollectItem-07-outline.png,
                 data/uprooted/CollectItem-08.png,
                 data/uprooted/CollectItem-08-faded.png,
                 data/uprooted/CollectItem-08-highlight.png,
                 data/uprooted/CollectItem-08-outline.png,

                 data/uprooted/Bark-01.png,
                 data/uprooted/Bark-02.png,
                 data/uprooted/Bark-03.png,
                 data/uprooted/Bark-04.png,
                 data/uprooted/Bark-05.png,
                 data/uprooted/Bark-06.png,
                 data/uprooted/Bark-07.png,
                 data/uprooted/SkywomanFall_Sprite-266x300.png,
                 data/uprooted/SkywomanHit_Sprite-266x267.png,
                 data/uprooted/Trunk.png,
                 data/uprooted/Water.png,

                 data/descent/descentBG.jpg,

                 data/descent/skywoman/SkyWomanJump_Sprite_new.png,
                 data/descent/skywoman/Skywomanrun_Sprite-237x260.png,
                 data/descent/bird sprites/Duck.png,
                 data/descent/bird sprites/Eagle.png,
                 data/descent/bird sprites/Goose.png,
                 data/descent/bird sprites/Loon.png,
                 data/descent/bird sprites/Raven.png,
                 data/descent/bird sprites/Seagull.png,
                 data/descent/bird sprites/Swan.png,
                 data/descent/turtle/Far-Turtle-ltr-800x271.png,
                 data/descent/clouds/B_Ground_Cloud_01.png,
                 data/descent/clouds/B_Ground_Cloud_02.png,
                 data/descent/clouds/B_Ground_Cloud_03.png,
                 data/descent/clouds/M_Ground_Cloud_01.png,
                 data/descent/clouds/M_Ground_Cloud_02.png,
                 data/descent/clouds/M_Ground_Cloud_03.png,
                 data/descent/clouds/M_Ground_Cloud_04.png,
                 data/descent/clouds/F_Ground_Cloud_01.png,
                 data/descent/clouds/F_Ground_Cloud_02.png,
                 data/descent/clouds/F_Ground_Cloud_03.png,

                 data/gifted/Background.png,
                 data/gifted/MuskratSwimDown_Sprite-162x247.png,
                 data/gifted/Muskrat_Chillin.png,
                 data/gifted/MuskratGrab_sprite_220x346.png,
                 data/gifted/MuskratSwimUp_Sprite_162x365.png,
                 data/gifted/MuskratSwimDown_Sprite-162x247_mask.png,
                 data/gifted/MuskratGrab_sprite_220x346_mask.png,
                 data/gifted/MuskratSwimUp_Sprite_162x365_mask.png,
                 data/gifted/MuskratSwimDownHIT_Sprite.png,
                 data/gifted/MuskratSwimUpHIT_Sprite.png,
                 data/gifted/DroppedMud_Sprite-100x280.png,
                 data/gifted/Coral_Reef-228x321.png,
                 data/gifted/SchoolFish_Sprite-280x260.png,
                 data/gifted/Whale_Sprite-330x209.png,
                 data/gifted/Salmon_Sprite-2127x107.png,
                 data/gifted/Shark_Sprite-434x195.png,
                 data/gifted/Eel_Sprite-175x35.png,
                 data/gifted/bubbles_sprite-183x381.png,
                 data/gifted/Light_Rays.png,
                 data/gifted/WaterTurtle_NEW_Sprite-219x378-2.png,
                 data/gifted/Directional_right.png,
                 data/gifted/Directional_left.png,

                 data/gifted/mountain/mountain-0.png,
                 data/gifted/mountain/mountain-1.png,
                 data/gifted/mountain/mountain-2.png,
                 data/gifted/mountain/mountain-3.png,
                 data/gifted/mountain/mountain-4.png,
                 data/gifted/mountain/mountain-5.png,
                 data/gifted/mountain/mountain-6.png,
                 data/gifted/mountain/mountain-7.png,
                 data/gifted/mountain/mountain-8.png,
                 data/gifted/mountain/mountain-9.png,


  
                 data/grounded/turtlesback_grounded_bg.png,
                 data/grounded/medicinewheel.png,
                 data/grounded/medicinewheel_arrowsyellow.png,
                 data/grounded/medicinewheel_arrowsblack.png,
                 data/grounded/medicinewheel_arrowsred.png,
                 data/grounded/medicinewheel_arrowswhite.png,
                 data/grounded/Turtle Island/pieces/start.png,
                 data/grounded/SkywomanIdle.png,
                 data/grounded/poses/colored/static-01.png,
                 data/grounded/poses/colored/static-02.png,
                 data/grounded/poses/colored/static-03.png,
                 data/grounded/poses/colored/static-04.png,
                 data/grounded/poses/colored/static-05.png,
                 data/grounded/poses/colored/static-06.png,
                 data/grounded/poses/colored/static-07.png,
                 data/grounded/poses/colored/static-08.png,
                 data/grounded/poses/colored/static-09.png,
                 data/grounded/poses/colored/static-10.png,
                 data/grounded/poses/colored/static-11.png,
                 data/grounded/poses/colored/static-12.png,
                 data/grounded/poses/silhouette/static-01.png,
                 data/grounded/poses/silhouette/static-02.png,
                 data/grounded/poses/silhouette/static-03.png,
                 data/grounded/poses/silhouette/static-04.png,
                 data/grounded/poses/silhouette/static-05.png,
                 data/grounded/poses/silhouette/static-06.png,
                 data/grounded/poses/silhouette/static-07.png,
                 data/grounded/poses/silhouette/static-08.png,
                 data/grounded/poses/silhouette/static-09.png,
                 data/grounded/poses/silhouette/static-10.png,
                 data/grounded/poses/silhouette/static-11.png,
                 data/grounded/poses/silhouette/static-12.png,

                 data/grounded/Fantastic_430x100.png,
    

  
                 data/grounded/Turtle Island/pieces/brown/piece-01.png,
                 data/grounded/Turtle Island/pieces/brown/piece-02.png,
                 data/grounded/Turtle Island/pieces/brown/piece-03.png,
                 data/grounded/Turtle Island/pieces/brown/piece-04.png,
                 data/grounded/Turtle Island/pieces/brown/piece-05.png,
                 data/grounded/Turtle Island/pieces/brown/piece-06.png,
                 data/grounded/Turtle Island/pieces/brown/piece-07.png,
                 data/grounded/Turtle Island/pieces/brown/piece-08.png,
                 data/grounded/Turtle Island/pieces/brown/piece-09.png,
                 data/grounded/Turtle Island/pieces/brown/piece-10.png,
                 data/grounded/Turtle Island/pieces/green/piece-01.png,
                 data/grounded/Turtle Island/pieces/green/piece-02.png,
                 data/grounded/Turtle Island/pieces/green/piece-03.png,
                 data/grounded/Turtle Island/pieces/green/piece-04.png,
                 data/grounded/Turtle Island/pieces/green/piece-05.png,
                 data/grounded/Turtle Island/pieces/green/piece-06.png,
                 data/grounded/Turtle Island/pieces/green/piece-07.png,
                 data/grounded/Turtle Island/pieces/green/piece-08.png,
                 data/grounded/Turtle Island/pieces/green/piece-09.png,
                 data/grounded/Turtle Island/pieces/green/piece-10.png,

                 data/grounded/Turtle Island/Turtle_Island_11_End.png"; 
*/
